product_bundle.content: 
    path: '/productbundle'
    defaults: 
      _controller: 'Drupal\product_bundle\Controller\ProductBundleController::content'
      _title: 'All Products Bundle'
    requirements:
      _permission: 'access content'